import Container from "../../components/Container";
import Heading from "../../components/Heading";
import Paragraph from "../../components/Paragraph";

export default function AboutUs() {
  return (
    <>
      <Container children={
        <>
          <Heading level={1} content="O nas" />
          <Paragraph content="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris et blandit ipsum. Duis quam ligula, luctus nec massa eu, pretium elementum purus. Phasellus tincidunt sem purus, vel laoreet massa imperdiet aliquet. Fusce vel suscipit orci. In sed neque nec libero imperdiet rhoncus. Ut porttitor ornare dolor vitae egestas. Maecenas eu augue quam. Curabitur at turpis sit amet tellus pellentesque aliquam vitae vitae est. Sed a leo quis felis volutpat egestas. Vivamus vulputate, dolor vitae sagittis aliquam, libero purus tempor turpis, sit amet varius odio leo id erat. Curabitur tempor varius augue, ut malesuada dolor lobortis non. Ut rhoncus erat et nisl consectetur, sed tristique metus iaculis. Phasellus faucibus magna in quam auctor egestas. Suspendisse rhoncus, ipsum in scelerisque eleifend, ante nisl auctor nibh, at mattis leo tortor in ipsum. Nulla facilisis enim eget magna malesuada fringilla. Nullam dignissim elit eget lectus blandit, eu bibendum ipsum fringilla. Integer tortor sem, elementum sed semper sed, molestie non dolor. Vestibulum consequat, tellus finibus porttitor dapibus, justo enim ornare metus, eu mattis arcu enim in lectus. Vivamus commodo tortor id imperdiet dapibus. Nam volutpat eu ex eu dictum. Morbi non pretium arcu, ac consequat libero. Nunc leo nunc, faucibus non ex sit amet, placerat scelerisque ipsum. Maecenas ullamcorper felis placerat urna facilisis, eget efficitur tortor pharetra. Integer congue imperdiet euismod. Pellentesque volutpat pulvinar nulla, placerat suscipit dui sodales ut. In eleifend molestie aliquet. Suspendisse volutpat, eros vulputate iaculis congue, mi enim rhoncus erat, a auctor metus dolor ut arcu. Morbi nec massa a ipsum hendrerit egestas. Donec convallis, leo non commodo eleifend, arcu sapien sollicitudin nunc, sed pellentesque odio purus at enim. Donec sagittis ac libero at sagittis. Suspendisse pellentesque aliquam enim at tempus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi venenatis mollis mollis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent non nulla vel orci dignissim tincidunt. Morbi varius molestie leo. Donec viverra scelerisque velit, id malesuada urna faucibus a. Donec tristique non magna sit amet dignissim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed eu erat lorem. Suspendisse." />
          <Heading level={2} content="Second heading" />
          <Paragraph content="Lorem ipsum dolor sit amet, consectetur adipiscing elit. In luctus, est in consequat venenatis, metus enim bibendum ligula, et sagittis augue sem non nulla. Phasellus elit lacus, finibus a feugiat sed, luctus id lacus. Mauris sollicitudin non ligula nec egestas. Ut feugiat nec enim eu rhoncus. Nam tellus turpis, finibus at varius in, pretium et justo. Sed dapibus diam ut lacus vestibulum aliquet. Mauris tincidunt dignissim nisl, et hendrerit nisi dapibus ac. Donec eget tempor turpis. Aenean lectus magna, pulvinar quis nibh quis, egestas efficitur orci. Nunc suscipit eget leo vel congue. Nunc quis faucibus turpis. Pellentesque et lacus augue. Morbi rhoncus elementum eros. Aenean quis mollis turpis. Mauris vulputate erat a tortor tempor pretium. Sed vehicula dapibus dui. Nunc ut nulla mollis, convallis massa a, venenatis nunc. Fusce cursus tempus mollis. Nullam eget elit dapibus, tincidunt quam vel, sollicitudin dolor. Maecenas feugiat magna et ante ullamcorper, in tempus felis laoreet. Ut nibh nibh, elementum et finibus eu, consequat id eros. Curabitur eu porta leo, a dapibus velit. Donec consectetur sem sit amet neque finibus, nec egestas dui consectetur. Phasellus fringilla ullamcorper quam, at placerat erat placerat nec. Pellentesque non euismod justo. Vivamus ac nibh elit. Donec massa justo, bibendum vitae mauris sed, pharetra finibus risus. Mauris ultricies viverra quam, sed eleifend mi. Aliquam euismod volutpat fermentum. Proin ultrices consectetur quam id lacinia. In vitae ex vel turpis feugiat varius et vitae nisi. Phasellus luctus sem et volutpat condimentum. Suspendisse nulla neque, posuere quis odio ut, congue aliquam arcu. Aenean ut."/>
        </>
      } />
    </>
  );
}